feat: check inventory when it's changed
Signed-off-by: joyceliu <joyceliu@yunify.com>

diff --git a/builtin/core/roles/init/init-artifact/tasks/download_binary.yaml b/builtin/core/roles/init/init-artifact/tasks/download_binary.yaml
--- a/builtin/core/roles/init/init-artifact/tasks/download_binary.yaml
+++ b/builtin/core/roles/init/init-artifact/tasks/download_binary.yaml
@@ -1,88 +1,88 @@
 ---
-- name: Check binaries for etcd
+- name: Binary | Ensure etcd binary is present
   tags: ["etcd"]
   command: |
     artifact_name={{ get .artifact.artifact_url.etcd .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/etcd/{{ .etcd_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
-        mkdir -p $artifact_path
-        # download online
-        http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.etcd .item }})
-        if [ $http_code != 200 ]; then
-          echo "http code is $http_code"
-          exit 1
-        fi
-        curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.etcd .item }}
+      mkdir -p $artifact_path
+      # Attempt to download etcd binary
+      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.etcd .item }})
+      if [ $http_code != 200 ]; then
+        echo "Failed to download etcd binary. HTTP status code: $http_code"
+        exit 1
+      fi
+      curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.etcd .item }}
     fi
   loop: "{{ .artifact.arch | toJson }}"
   when: .etcd_version | empty | not
 
-- name: Check binaries for kube
+- name: Binary | Ensure Kubernetes binaries are present
   tags: ["kube"]
   command: |
     kube_path={{ .binary_dir }}/kube/{{ .kube_version }}/{{ .item }}
     if [ ! -f $kube_path/kubelet ]; then
-        mkdir -p $kube_path
-        # download online
-        http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubelet .item }})
-        if [ $http_code != 200 ]; then
-          echo "http code is $http_code"
-          exit 1
-        fi
-        curl -L -o $kube_path/kubelet {{ get .artifact.artifact_url.kubelet .item }}
+      mkdir -p $kube_path
+      # Download kubelet if missing
+      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubelet .item }})
+      if [ $http_code != 200 ]; then
+        echo "Failed to download kubelet. HTTP status code: $http_code"
+        exit 1
+      fi
+      curl -L -o $kube_path/kubelet {{ get .artifact.artifact_url.kubelet .item }}
     fi
     if [ ! -f $kube_path/kubeadm ]; then
-        mkdir -p $kube_path
-        # download online
-        http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubeadm .item }})
-        if [ $http_code != 200 ]; then
-          echo "http code is $http_code"
-          exit 1
-        fi
-        curl -L -o $kube_path/kubeadm {{ get .artifact.artifact_url.kubeadm .item }}
+      mkdir -p $kube_path
+      # Download kubeadm if missing
+      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubeadm .item }})
+      if [ $http_code != 200 ]; then
+        echo "Failed to download kubeadm. HTTP status code: $http_code"
+        exit 1
+      fi
+      curl -L -o $kube_path/kubeadm {{ get .artifact.artifact_url.kubeadm .item }}
     fi
     if [ ! -f $kube_path/kubectl ]; then
-        mkdir -p $kube_path
-        # download online
-        http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubectl .item }})
-        if [ $http_code != 200 ]; then
-          echo "http code is $http_code"
-          exit 1
-        fi
-        curl -L -o $kube_path/kubectl {{ get .artifact.artifact_url.kubectl .item }}
+      mkdir -p $kube_path
+      # Download kubectl if missing
+      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.kubectl .item }})
+      if [ $http_code != 200 ]; then
+        echo "Failed to download kubectl. HTTP status code: $http_code"
+        exit 1
+      fi
+      curl -L -o $kube_path/kubectl {{ get .artifact.artifact_url.kubectl .item }}
     fi
   loop: "{{ .artifact.arch | toJson }}"
   when: .kube_version | empty | not
 
-- name: Check binaries for cni
+- name: Binary | Ensure CNI plugins are present
   tags: ["cni"]
   command: |
     artifact_name={{ get .artifact.artifact_url.cni_plugins .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/cni/plugins/{{ .cni_plugins_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
-        http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.cni_plugins .item }})
-        if [ $http_code != 200 ]; then
-          echo "http code is $http_code"
-          exit 1
-        fi
+      # Attempt to download CNI plugins
+      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.cni_plugins .item }})
+      if [ $http_code != 200 ]; then
+        echo "Failed to download CNI plugins. HTTP status code: $http_code"
+        exit 1
+      fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.cni_plugins .item }}
     fi
   loop: "{{ .artifact.arch | toJson }}"
   when: .cni_plugins_version | empty | not
 
-- name: Check binaries for helm
+- name: Binary | Ensure Helm binary is present
   tags: ["helm"]
   command: |
     artifact_name={{ get .artifact.artifact_url.helm .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/helm/{{ .helm_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download Helm binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.helm .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download Helm binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.helm .item }}
@@ -90,17 +90,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .helm_version | empty | not
 
-- name: Check binaries for crictl
+- name: Binary | Ensure crictl binary is present
   tags: ["crictl"]
   command: |
     artifact_name={{ get .artifact.artifact_url.crictl .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/crictl/{{ .crictl_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download crictl binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.crictl .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download crictl binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.crictl .item }}
@@ -108,17 +108,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .crictl_version | empty | not
 
-- name: Check binaries for docker
+- name: Binary | Ensure Docker binary is present
   tags: ["docker"]
   command: |
     artifact_name={{ get .artifact.artifact_url.docker .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/docker/{{ .docker_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download Docker binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.docker .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download Docker binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.docker .item }}
@@ -126,17 +126,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .docker_version | empty | not
 
-- name: Check binaries for cridockerd
+- name: Binary | Ensure cri-dockerd binary is present
   tags: ["cridockerd"]
   command: |
     artifact_name={{ get .artifact.artifact_url.cridockerd .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/cri-dockerd/{{ .cridockerd_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download cri-dockerd binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.cridockerd .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download cri-dockerd binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.cridockerd .item }}
@@ -144,17 +144,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .cridockerd_version | empty | not
 
-- name: Check binaries for containerd
+- name: Binary | Ensure containerd binary is present
   tags: ["containerd"]
   command: |
     artifact_name={{ get .artifact.artifact_url.containerd .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/containerd/{{ .containerd_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download containerd binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.containerd .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download containerd binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.containerd .item }}
@@ -162,17 +162,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .containerd_version | empty | not
 
-- name: Check binaries for runc
+- name: Binary | Ensure runc binary is present
   tags: ["runc"]
   command: |
     artifact_name={{ get .artifact.artifact_url.runc .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/runc/{{ .runc_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download runc binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.runc .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download runc binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.runc .item }}
@@ -180,17 +180,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .runc_version | empty | not
 
-- name: Check binaries for calicoctl
+- name: Binary | Ensure calicoctl binary is present
   tags: ["calicoctl"]
   command: |
     artifact_name=calicoctl
     artifact_path={{ .binary_dir }}/cni/calico/{{ .calico_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download calicoctl binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.calicoctl .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download calicoctl binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.calicoctl .item }}
@@ -198,17 +198,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .calico_version | empty | not
 
-- name: Check binaries for registry
+- name: Binary | Ensure Docker Registry binary is present
   tags: ["registry"]
   command: |
     artifact_name={{ get .artifact.artifact_url.docker_registry .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/image-registry/docker-registry/{{ .docker_registry_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download Docker Registry binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.docker_registry .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download Docker Registry binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.docker_registry .item }}
@@ -216,30 +216,30 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .docker_registry_version | empty | not
 
-- name: Check binaries for docker-compose
+- name: Binary | Ensure docker-compose binary is present
   tags: ["docker-compose"]
   command: |
     compose_name=docker-compose
     compose_path={{ .binary_dir }}/image-registry/docker-compose/{{ .dockercompose_version }}/{{ .item }}
     if [ ! -f $compose_path/$compose_name ]; then
       mkdir -p $compose_path
-      # download online
+      # Attempt to download docker-compose binary
       curl -L -o $compose_path/$compose_name {{ get .artifact.artifact_url.dockercompose .item }}
     fi
   loop: "{{ .artifact.arch | toJson }}"
   when: .dockercompose_version | empty | not
 
-- name: Check binaries for harbor
+- name: Binary | Ensure Harbor binary is present
   tags: ["harbor"]
   command: |
     harbor_name={{ get .artifact.artifact_url.harbor .item | splitList "/" | last }}
     harbor_path={{ .binary_dir }}/image-registry/harbor/{{ .harbor_version }}/{{ .item }}
     if [ ! -f $harbor_path/$harbor_name ]; then
       mkdir -p $harbor_path
-      # download online
+      # Attempt to download Harbor binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.harbor .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download Harbor binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $harbor_path/$harbor_name {{ get .artifact.artifact_url.harbor .item }}
@@ -247,17 +247,17 @@
   loop: "{{ .artifact.arch | toJson }}"
   when: .harbor_version | empty | not
 
-- name: Check binaries for keepalived
+- name: Binary | Ensure keepalived binary is present
   tags: ["keepalived"]
   command: |
     artifact_name={{ get .artifact.artifact_url.keepalived .item | splitList "/" | last }}
     artifact_path={{ .binary_dir }}/image-registry/keepalived/{{ .keepalived_version }}/{{ .item }}
     if [ ! -f $artifact_path/$artifact_name ]; then
       mkdir -p $artifact_path
-      # download online
+      # Attempt to download keepalived binary
       http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.keepalived .item }})
       if [ $http_code != 200 ]; then
-        echo "http code is $http_code"
+        echo "Failed to download keepalived binary. HTTP status code: $http_code"
         exit 1
       fi
       curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.keepalived .item }}
