feat: enhance precheck tasks for image registry and network validation (#2676)
* feat: enhance precheck tasks for image registry and network validation

- Added a task to ensure successful authentication to the image registry.
- Updated existing tasks to provide clearer failure messages for required configurations.
- Improved validation for network interfaces and CIDR configurations, ensuring dual-stack support.
- Enhanced error handling in the resource handler for playbook creation.

Signed-off-by: joyceliu <joyceliu@yunify.com>

* feat: enhance configuration and query handling

- Added `-trimpath` flag to Go build configuration for improved binary paths.
- Updated REST configuration to set QPS and Burst limits for better performance.
- Refactored query handling to use string types for field and value, improving type consistency.
- Enhanced error handling in resource configuration updates and improved parsing of request bodies.

Signed-off-by: joyceliu <joyceliu@yunify.com>

* feat: check inventory when it's changed

Signed-off-by: joyceliu <joyceliu@yunify.com>

* feat: enhance playbook execution and query handling

- Added a new optional query parameter `promise` to the playbook and inventory endpoints, allowing for asynchronous execution control.
- Introduced a new result state `ResultPending` to indicate ongoing operations.
- Refactored the executor function to handle the `promise` parameter, enabling conditional execution of playbooks.
- Improved error handling and logging during playbook execution.

Signed-off-by: joyceliu <joyceliu@yunify.com>

---------

Signed-off-by: joyceliu <joyceliu@yunify.com>

diff --git a/builtin/core/roles/precheck/env_check/tasks/image_registry.yaml b/builtin/core/roles/precheck/env_check/tasks/image_registry.yaml
--- a/builtin/core/roles/precheck/env_check/tasks/image_registry.yaml
+++ b/builtin/core/roles/precheck/env_check/tasks/image_registry.yaml
@@ -1,18 +1,29 @@
+- name: Ensure image registry authentication is successful
+  when: .image_registry.auth | empty | not
+  run_once: true
+  command: |
+    HTTP_CODE=$(curl -skLI -w "%{http_code}" -u "{{ .image_registry.auth.username }}:{{ .image_registry.auth.password }}" "https://{{ .image_registry.auth.registry }}/v2/" -o /dev/null)
+    if [[ "$HTTP_CODE" == "200" ]]; then
+      echo "Authentication to image registry succeeded."
+    else
+      echo "Authentication to image registry {{ .image_registry.auth.registry }} failed." >&2
+    fi
+
 # image_registry is installed by docker_compose
-- name: docker_version and dockercompose_version should not be empty
+- name: Ensure docker and docker-compose versions are set for image registry
   when: .groups.image_registry | empty | not
   assert:
     that:
      - .docker_version | empty | not
      - .dockercompose_version | empty | not
     msg: >-
-      "docker_version" and "dockercompose_version" should not be empty
+      Both "docker_version" and "dockercompose_version" must be specified for the image registry.
 
-- name: keepalived_version should not be empty when image_registry is high availability
+- name: Ensure keepalived_version is set for high availability image registry
   when: 
     - .image_registry.ha_vip | empty | not
     - .groups.image_registry | len | lt 1
   assert:
     that: .keepalived_version | empty | not
     msg: >-
-      "keepalived_version" should not be empty when image_registry is high availability
+      "keepalived_version" must be specified when the image registry is configured for high availability.
