feat: install image_registry (#2640)
Signed-off-by: joyceliu <joyceliu@yunify.com>

diff --git a/builtin/core/roles/install/image-registry/tasks/install_harbor.yaml b/builtin/core/roles/install/image-registry/tasks/install_harbor.yaml
--- a/builtin/core/roles/install/image-registry/tasks/install_harbor.yaml
+++ b/builtin/core/roles/install/image-registry/tasks/install_harbor.yaml
@@ -2,7 +2,7 @@
 - name: Sync harbor package to remote
   copy:
     src: >-
-      {{ .binary_dir }}/image-registry/harbor/{{ .harbor_version }}/{{ .binary_type.stdout }}/harbor-offline-installer-{{ .harbor_version }}.tgz
+      {{ .binary_dir }}/image-registry/harbor/{{ .harbor_version }}/{{ .binary_type }}/harbor-offline-installer-{{ .harbor_version }}.tgz
     dest: >-
       /opt/harbor/{{ .harbor_version }}/harbor-offline-installer-{{ .harbor_version }}.tgz
 
@@ -30,15 +30,6 @@
     dest: >-
       /opt/harbor/{{ .harbor_version }}/harbor/harbor.yml
 
-- name: Generate keepalived docker compose
-  template:
-    src: harbor_keepalived.docker-compose
-    dest: >-
-      /opt/harbor/{{ .harbor_version }}/harbor/docker-compose-keepalived.yml
-  when:
-    - .image_registry.ha_vip | empty | not
-    - .image_registry_service.stderr | empty | not
-
 - name: Install harbor
   command: |
     cd /opt/harbor/{{ .harbor_version }}/harbor && /bin/bash install.sh
@@ -50,3 +41,62 @@
 
 - name: Start harbor service
   command: systemctl daemon-reload && systemctl start harbor.service && systemctl enable harbor.service
+
+- name: HA harbor sync images
+  when:
+    - .image_registry.ha_vip | empty | not
+    - .groups.image_registry | len | lt 1
+  block:
+    - name: add keepalived service to docker-compose
+      command: |
+        KEEPALIVED_SERVICE='# keepalived is generated by kubekey.
+          keepalived:
+            image: osixia/keepalived:{{ .keepalived_version }}
+            container_name: keepalived
+            command:
+              - --copy-service
+            network_mode: "host"
+            restart: always
+            dns_search: .
+            cap_drop:
+              - ALL
+            cap_add:
+              - NET_ADMIN
+              - NET_BROADCAST
+              - NET_RAW
+              - CHOWN
+              - DAC_OVERRIDE
+            depends_on:
+              - proxy
+            volumes:
+              - type: bind
+                source: /opt/keepalived/{{ .keepalived_version }}/keepalived.conf
+                target: /container/service/keepalived/assets/keepalived.conf
+              - type: bind
+                source: /opt/keepalived/{{ .keepalived_version }}/healthcheck.sh
+                target: /etc/keepalived/healthcheck.sh'
+        TARGET_FILE="/opt/harbor/{{ .harbor_version }}/harbor/docker-compose.yml"
+        TMP_FILE="/opt/harbor/{{ .harbor_version }}/harbor/docker-compose.yml.tmp"
+        awk -v service="$KEEPALIVED_SERVICE" '
+          /^services:/ {
+            print
+            print service
+            next
+          }
+          { print }
+        ' "$TARGET_FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$TARGET_FILE"
+        systemctl restart harbor.service
+    - name: wait harbor service ready
+      command: |
+        if ! timeout 300 bash -c 'while ! nc -zv localhost 443; do sleep 2; done'; then
+            echo "ERROR: Harbor did not start within 5 minutes!"
+            exit 1
+        fi
+    - name: sync harbor-replications scripts to remote
+      template:
+        src: harbor-replications.sh
+        dest: /opt/harbor/scripts/harbor-replications.sh
+        mode: 0755
+    - name: execute harbor-replications.sh
+      command: bash /opt/harbor/scripts/harbor-replications.sh
+          
