dev-v2.0.0: add AutoRenewCertsModule
Signed-off-by: 24sama <leo@kubesphere.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,6 +33,15 @@ jobs:
       - name: Downloading go dependencies
         run: go mod tidy
 
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy.
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo 'To fix this check, run "go mod tidy"'
+            git status # Show the files that failed to pass the check.
+            exit 1
+          fi
+
       - name: Build
         run: go build -v -o output/kk ./main.go
 
